import "../styles/globals.css";
import type { AppProps } from "next/app";
import Head from "next/head";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="apple-itunes-app"
          content="app-id=1529224299, app-argument=https://apps.apple.com/ru/app/spectrumdata/id1529224299"
        />
        <link rel="icon" href="/favicon.ico" />
        <link rel="canonical" href={process.env.NEXT_PUBLIC_URL} />
      </Head>

      <Component {...pageProps} />
    </>
  );
}

export default MyApp;
