import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import useExperiment from "../hooks/useExperiment";
import First from "./first";
import Second from "./second";
import styles from "./index.module.css";

const Home: NextPage = () => {
  const variant = useExperiment("i2Ri3Ga8SoKm_p1maUngGA");
  console.log(variant);
  console.log(typeof variant);

  if (variant === "1") {
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link rel="canonical" href={process.env.NEXT_PUBLIC_URL} />
    </Head>;
    return <First />;
  }

  if (variant === "2") {
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link rel="canonical" href={process.env.NEXT_PUBLIC_URL} />
    </Head>;
    return <Second />;
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="canonical" href={process.env.NEXT_PUBLIC_URL} />
      </Head>

      <div className={styles["container"]}>
        QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQqq
      </div>
    </div>
  );
};

export default Home;
